#
#   Defines
#
BASEDIR		:=	../

CFLAGS		:=	-std=c++11

INCLUDES	:= \
	-I./ \
	-I$(BASEDIR) \

LIBS		:= \

APPEND_OBJS := \

SUBDIRS		:= \

#
#   Target object
#
TARGET_NAME	:=	section_parser

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	SHARED

#
#   Compile sources
#
SRCS		:=

SRCS_CPP	:= \
	SectionParser.cpp \


#
#   Configurations
#
include $(BASEDIR)/Config.mak

