#
#   Defines
#
BASEDIR		:=	../../
CFLAGS		:=	-std=c++11 -fPIC
INCLUDES	:= \
	-I./ \
	-I../ \
	-I../../ \
	-I../aribstr \

LIBS		:=


#
#   Target object
#
TARGET_NAME	:=	descriptor

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	OBJECT

#
#   Compile sources
#
SRCS		:=

SRCS_CPP	:= \
	Descriptor.cpp \
	ShortEventDescriptor.cpp \


#
#   Configurations
#
include $(BASEDIR)/Config.mak

