#
#   Defines
#
BASEDIR		:=	../../
CFLAGS		:=	-std=c++11 -fPIC
INCLUDES	:= \
	-I./ \
	-I$(BASEDIR) \
	-I$(BASEDIR)/psisi \
	-I$(BASEDIR)/aribstr \

LIBS		:=


#
#   Target object
#
TARGET_NAME	:=	descriptor

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	OBJECT

#
#   Compile sources
#
SRCS		:=

SRCS_CPP	:= \
	Descriptor.cpp \
	ShortEventDescriptor.cpp \
	ExtendedEventDescriptor.cpp \
	ComponentDescriptor.cpp \
	AudioComponentDescriptor.cpp \
	SeriesDescriptor.cpp \
	ContentDescriptor.cpp \


#
#   Configurations
#
include $(BASEDIR)/Config.mak

