#
#   Defines
#
BASEDIR		:=	./

INCLUDES	:= -I./cereal/include

LIBS		:=

LDFLAGS		:=

APPEND_OBJS	:=

SUBDIRS		:=

USERDEFS	:= -std=c++11


#
#   Target object
#
TARGET_NAME	:=	testcereal

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	EXEC

#
#   Compile sources
#
SRCS		:=

SRCS_CPP	:= test.cpp Etime.cpp


#
#   Configurations
#
include $(BASEDIR)/Config.mak

