all:
  children:
    local:
      hosts:
        localhost:
          ansible_host: localhost
          ansible_user: "{{ stage_user }}"
          ansible_ssh_pass: "{{ stage_pass }}"

    dev_all:
      hosts:
        dev_0:
          ansible_host: 192.168.50.200
          ansible_user: "{{ stage_user }}"
          ansible_ssh_pass: "{{ stage_pass }}"

        dev_1:
          ansible_host: 192.168.50.201
          ansible_user: "{{ stage_user }}"
          ansible_ssh_pass: "{{ stage_pass }}"


